### ISSUE TITLE
[BUG] Crash with "The Legend of Herobrine" mod

### ISSUE THREAD

**Issue by FosyaFox** [theomenden/TheOmenDen.Vanadium#43]
Caused by: java.lang.IllegalStateException: Errors during registry creation
    at net.minecraft.class_7877$class_7878.method_46798(class_7877.java:137)
    at net.minecraft.class_7877.method_46780(class_7877.java:269)
    at net.minecraft.class_7887.method_46817(class_7887.java:96)
    at vanadium.utils.SimpleBiomeRegistryUtils.<clinit>(SimpleBiomeRegistryUtils.java:30)
    ... 21 more
    Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / herobrine:cursed_forest]
        at net.minecraft.class_7877$class_7878.method_46797(class_7877.java:128)
        at net.minecraft.class_7877.method_46780(class_7877.java:268)
        ... 23 more

**Comment by AlucardMG36** [comment]
This is an issue with the way the registries are not being refreshed at the correct time.
A fix for this here, and a hot fix in Bismuth are on the way.

**Comment by SettingDust** [comment]
Another one
```
Caused by: java.lang.IllegalStateException: Errors during registry creation
	at MC//net.minecraft.registry.RegistryBuilder$Registries.throwErrors(RegistryBuilder.java:137)
	at MC//net.minecraft.registry.RegistryBuilder.createWrapperLookup(RegistryBuilder.java:269)
	at MC//net.minecraft.registry.BuiltinRegistries.createWrapperLookup(BuiltinRegistries.java:96)
	at vanadium.utils.SimpleBiomeRegistryUtils.<clinit>(SimpleBiomeRegistryUtils.java:46)
	... 41 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / galosphere:lichen_caves]
		at MC//net.minecraft.registry.RegistryBuilder$Registries.validateReferences(RegistryBuilder.java:128)
		at MC//net.minecraft.registry.RegistryBuilder.createWrapperLookup(RegistryBuilder.java:268)
		... 43 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / profundis:mushroom_caves]
		at MC//net.minecraft.registry.RegistryBuilder$Registries.validateReferences(RegistryBuilder.java:128)
		at MC//net.minecraft.registry.RegistryBuilder.createWrapperLookup(RegistryBuilder.java:268)
		... 43 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / profundis:arid_caves]
		at MC//net.minecraft.registry.RegistryBuilder$Registries.validateReferences(RegistryBuilder.java:128)
		at MC//net.minecraft.registry.RegistryBuilder.createWrapperLookup(RegistryBuilder.java:268)
		... 43 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / profundis:floral_lush_caves]
		at MC//net.minecraft.registry.RegistryBuilder$Registries.validateReferences(RegistryBuilder.java:128)
		at MC//net.minecraft.registry.RegistryBuilder.createWrapperLookup(RegistryBuilder.java:268)
		... 43 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / profundis:frozen_caves]
		at MC//net.minecraft.registry.RegistryBuilder$Registries.validateReferences(RegistryBuilder.java:128)
		at MC//net.minecraft.registry.RegistryBuilder.createWrapperLookup(RegistryBuilder.java:268)
		... 43 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / profundis:molten_caves]
		at MC//net.minecraft.registry.RegistryBuilder$Registries.validateReferences(RegistryBuilder.java:128)
		at MC//net.minecraft.registry.RegistryBuilder.createWrapperLookup(RegistryBuilder.java:268)
		... 43 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / galosphere:crystal_canyons]
		at MC//net.minecraft.registry.RegistryBuilder$Registries.validateReferences(RegistryBuilder.java:128)
		at MC//net.minecraft.registry.RegistryBuilder.createWrapperLookup(RegistryBuilder.java:268)
		... 43 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / profundis:black_caves]
		at MC//net.minecraft.registry.RegistryBuilder$Registries.validateReferences(RegistryBuilder.java:128)
		at MC//net.minecraft.registry.RegistryBuilder.createWrapperLookup(RegistryBuilder.java:268)
		... 43 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / profundis:amethyst_caves]
		at MC//net.minecraft.registry.RegistryBuilder$Registries.validateReferences(RegistryBuilder.java:128)
		at MC//net.minecraft.registry.RegistryBuilder.createWrapperLookup(RegistryBuilder.java:268)
		... 43 more
```
